Repository pivotal-cf/docs-redis, pull requests merged in 2018-05, with the labels that each got.

#164 [1.12] Clarify that redis-ODB will fail an update-service if arbitrary parameters are changed
  release.html.md.erb
Labels: unscheduled

#166 [1.10] Clarify that redis-ODB will fail an update-service if arbitrary parameters are changed
  release.html.md.erb
Labels: unscheduled

#165 [1.11] Clarify that redis-ODB will fail an update-service if arbitrary parameters are changed
  release.html.md.erb
Labels: unscheduled

#167 Add details on limitations changing AZs or network
  upgrade.html.md.erb
Labels: unscheduled

#168 Add details on limitations changing AZs or network
  upgrade.html.md.erb
Labels: unscheduled

#169 Add details on limitations changing AZs or network
  upgrade.html.md.erb
Labels: unscheduled

#170 Add details on limitations changing AZs or network
  upgrade.html.md.erb
Labels: unscheduled

#176 clarify effect of CIDR changes and network changes for shared
  upgrade.html.md.erb
Labels: scheduled

#175 clarify effect of CIDR changes and network changes for shared
  upgrade.html.md.erb
Labels: scheduled

#174 clarify effect of CIDR changes and network changes for shared
  upgrade.html.md.erb
Labels: scheduled

#173 clarify effect of CIDR changes and network changes for shared
  upgrade.html.md.erb
Labels: scheduled

#172 Secure service instance sharing
  installing.html.md.erb
  release.html.md.erb
Labels: scheduled

#177 1.13 smoke test update
  smoke-tests.html.md.erb
Labels: unscheduled

#181 Update secure credentials to reflect removal of redis tile property
  installing.html.md.erb
Labels: unscheduled

#182 1.12.1 Release Notes
  release.html.md.erb
Labels: in progress

#178 Update smoke test docs to include new service-key step
  smoke-tests.html.md.erb
Labels: unscheduled

#184 Odb upgrade canaries
  images/canary-options.png
  images/redis-odservice-settings.png
  installing.html.md.erb
  release.html.md.erb
Labels: unscheduled
