Repository pivotal-cf/docs-redis, pull requests merged in 2019-03, with the labels that each got.

#339 Document BOSH HotSwaps feature
  release.html.md.erb
  upgrade.html.md.erb
Labels: unscheduled

#340 Add documentation on originating service instance type for redis metrics
  monitoring.html.md.erb
Labels: unscheduled

#341 Add security fix entry for Redis 5.0 bump
  index.html.md.erb
  release.html.md.erb
Labels: unscheduled

#343 Add warning not to set Outbound Internet Access for Azure AZs installation
  _warning-azure-outbound-internet-access.html.md.erb
  installing.html.md.erb
  release.html.md.erb
Labels: unscheduled

#342 Added release notes for tile_installer_client use for errands.
  release.html.md.erb
Labels: scheduled

#344 Add troubleshooting notes on how to restore a wrongly purged service instance
  troubleshooting.html.md.erb
Labels: unscheduled

#345 [Redis] Add missing step to transfer artefact to new service isntance
  troubleshooting.html.md.erb
Labels: unscheduled

#346 [2.0] Add warning to suggest restarting odb after 2.3->2.4 upgrade
  release.html.md.erb
Labels: unscheduled

#349 Update docs to reflect redis version bump
  index.html.md.erb
  release.html.md.erb
Labels: unscheduled

#350 Document downtime reduction with BOSH HotSwaps
  upgrade.html.md.erb
Labels: unscheduled

#348 Document new clearer error message
  release.html.md.erb
Labels: unscheduled

#351 Add further documentation about BOSH HotSwaps benefits.
  upgrade.html.md.erb
Labels: unscheduled

#352 [2.1] Configuring Shared-VMs via arbitrary params is not supported
  architecture-pp.html.md.erb
  using.html.md.erb
Labels: in progress

#353 [1.14] Configuring Shared-VMs via arbitrary params is not supported
  architecture-pp.html.md.erb
  using.html.md.erb
Labels: in progress

#355 [1.13] Configuring Shared-VMs via arbitrary params is not supported
  architecture-pp.html.md.erb
  using.html.md.erb
Labels: in progress

#359 [1.13] Add instructions on how to fix AOF file if file is corrupted at startup
  troubleshooting.html.md.erb
Labels: unscheduled

#358 [1.14] Add instructions on how to fix AOF file if file is corrupted at startup
  troubleshooting.html.md.erb
Labels: unscheduled

#357 [2.0] Add instructions on how to fix AOF file if file is corrupted at startup
  troubleshooting.html.md.erb
Labels: unscheduled

#356 [2.1] Add instructions on how to fix AOF file if file is corrupted at startup
  troubleshooting.html.md.erb
Labels: unscheduled

#360 Add release notes and docs for shared-VM lua scripting toggling
  architecture-pp.html.md.erb
  installing.html.md.erb
  release.html.md.erb
Labels: unscheduled

#361 Document firehose deprecation and RLP/Log-Cache recommendation
  monitoring.html.md.erb
  release.html.md.erb
Labels: unscheduled

#363 Add fix for cf-redis-broker metrics issue to release notes
  release.html.md.erb
Labels: unscheduled

#364 [2.0] Add known issues for cf-redis-broker metrics
  release.html.md.erb
Labels: unscheduled

#365 [1.14] Add known issues for cf-redis-broker metrics
  release.html.md.erb
Labels: unscheduled

#367 Document service backup scp as known issue.
  release.html.md.erb
Labels: unscheduled

#368 1.14 service backups issue 164930374
  release.html.md.erb
Labels: unscheduled

#369 Document service backup failure with stemcell 170.30+ as known issue.
  release.html.md.erb
Labels: unscheduled

#371 Add how to retrieve shared-instance-guid for shared-vms
  monitoring.html.md.erb
Labels: unscheduled

#370 Document service backup bump to fix scp issue
  release.html.md.erb
Labels: in progress

#362 Update image for shared-vm config to include lua toggle
  images/shared-vm-config.png
Labels: unscheduled

#374 Updates compatability matrix for 2.1.0.
  release.html.md.erb
Labels: unscheduled
