Repository pivotal-cf/docs-redis, pull requests merged in 2019-05, with the labels that each got.

#380 Document max shared instance limit
  architecture-pp.html.md.erb
Labels: unscheduled

#366 1.13.9 release notes
  index.html.md.erb
  maintain.html.md.erb
  release.html.md.erb
Labels: scheduled

#373 2.0.2 release notes
  index.html.md.erb
  maintain.html.md.erb
  release.html.md.erb
Labels: scheduled

#372 1.14.6 release notes
  index.html.md.erb
  maintain.html.md.erb
  release.html.md.erb
Labels: in progress

#381 Aws upgrade issue.
  release.html.md.erb
Labels: unscheduled

#382 release notes for 2.1.2
  release.html.md.erb
Labels: unscheduled

#383 Document multi-az manual upgrade step.
  upgrade.html.md.erb
Labels: unscheduled
